// Generated by tools/extract_levels.py -- do not edit by hand.
// Source: the original iOS Double Maze level%d.txt / level%dPOS.txt files.

#ifndef DOUBLE_MAZE_LEVELS_H
#define DOUBLE_MAZE_LEVELS_H

#include <tonc.h>

#define GRID_W 15
#define GRID_H 8
#define GRID_AREA (GRID_W * GRID_H)
#define LEVEL_COUNT 40

// Per-tile bitfield. A WALL_* bit means you may NOT leave the tile that way;
// entering a tile additionally requires its opposite edge to be open.
#define WALL_UP     0x01
#define WALL_DOWN   0x02
#define WALL_LEFT   0x04
#define WALL_RIGHT  0x08
#define FLAG_FINISH 0x10
#define FLAG_DEATH  0x20

typedef struct LevelData
{
    u8 number;              // original level number, 1-based
    u8 left_x,  left_y;     // starting cell for the left ball
    u8 right_x, right_y;    // starting cell for the right ball
    u8 tiles[GRID_AREA];    // raw tile ids, 0-15
    u8 flags[GRID_AREA];    // tiles[] pre-decoded into the bitfield above
} LevelData;

extern const LevelData g_levels[LEVEL_COUNT];

#endif // DOUBLE_MAZE_LEVELS_H
