// Generated by tools/make_assets.py -- do not edit by hand.

#ifndef DOUBLE_MAZE_SKINS_H
#define DOUBLE_MAZE_SKINS_H

#include <tonc.h>

#define CELL_PX      16
#define SKIN_COUNT   3
#define MT_COUNT     27   // 16 ids + 5 lit goals + 6 carrying a lip
#define MT_TILES     4    // hardware tiles per 16x16 metatile

// Sprite strip: metatile 0 is the ball, then the death sequence.
#define SPR_BALL        0
#define SPR_DEATH_FIRST 1
#define SPR_DEATH_COUNT 19

// Backdrop colour behind the void tiles, sampled from each skin's iOS
// background image. palettes.h carries the high-contrast variant.
static const COLOR skin_backdrop[SKIN_COUNT] = { 0x1084, 0x2ADE, 0x16B1 };

// Lit variant for each tile id; a non-goal tile maps to itself.
static const u8 mt_lit[16] = {
    0, 1, 2, 3, 4, 16, 6, 7, 8, 9, 10, 17, 18, 19, 20, 15
};

// Variant carrying the overhanging lip of the tile above, or itself
// for tiles that paint over it. Indexed by metatile, so it composes
// after mt_lit.
static const u8 mt_toplip[MT_COUNT] = {
    0, 1, 2, 3, 4, 5, 21, 22, 23, 24, 25, 11, 12, 13, 14, 26, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26
};

// Which edges each tile id walls off, as EDGE_* bits. Note tile 15
// draws all four walls but is passable in every direction -- that
// inconsistency is in the original, and this table is about looks.
#define EDGE_TOP    1
#define EDGE_RIGHT  2
#define EDGE_BOTTOM 4
#define EDGE_LEFT   8

static const u8 tile_wall_edges[16] = {
    0, 1, 2, 4, 8, 0, 0, 1, 2, 4, 8, 1, 2, 4, 8, 15
};

// Whether a tile paints a floor or target of its own -- and so has a
// lip that overhangs the cell below it.
static const u8 tile_draws_image[16] = {
    1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0
};

#endif // DOUBLE_MAZE_SKINS_H
